### ISSUE TITLE
reloading the grid after changes in the grid-data

### ISSUE THREAD

**Issue by Naveen-ASI** [angular-data-grid/angular-data-grid.github.io#34]
Hi,
this project is excellent it saved lot of my work. but now i have running in new problem. In my case my grid display all user information as each user per row and also I have a button where we can add new user but the thing is when I add new User , server return new added user data with id (primary Id). I need to push this new user object to grid.data array, using this 
                                               $scope.gridOptions.data.push(addedUserDetails);
its successfully pushing the data but its not automatically binding in the grid view. I want finish this work as soon as possible. anyone please help me in this regards.

**Comment by tina-tran** [comment]
Hi, 

I'm dealing with the same scenario: adding a new row to the grid. My issue is **the new row only shows up when I sort the grid** (by any column, it does not matter) by clicking on a sortable header
I tried to use the following functions after pushing the new data to $scope.gridActions.data:
- $scope.gridActions.refresh();
- $scope.gridOptions.grid.reloadGrid();
Nothing worked..
Here is an example forked from the demo code: http://codepen.io/7in4/pen/jmNbpJ

I'm still searching a solution and I would really appreciate any help.

Kind regards,
Tina.

**Comment by AlexanderZhukCoherent** [comment]
@tina-tran Can you please re-verify after the latest fix (6166777) by Igor?

**Comment by Naveen-ASI** [comment]
i have got it work. the thing is create empty object and assign that to grid-actions attribute like this 
grid-actions="groupGridActions"
and when you add new entry to data , call groupGridActions.refresh() function like this 
$scope.groupGridOptions.data.push(newGroupDetails);
$scope.groupGridActions.refresh();

**Comment by AlexanderZhukCoherent** [comment]
@Naveen-ASI - we already fixed that in data grid code, please check with the latest sources.

**Comment by tina-tran** [comment]
@AlexanderZhukCoherent Thank you so much. You have just saved me a ton of time. It works great.
@Naveen-ASI I did initialise grid-actions with an empty object and call $scope.groupGridActions.refresh(); but it didn't work before the last commit of @korshuk 

Thank you again for this amazing project! 👍

**Comment by suvonkar** [comment]
I am also facing the same issue at the time of refresh. 

My initial grid loading code.

```
$rootScope.gridOptions = {
        data: [],
        urlSync: false,
        sort: {
            predicate: 'empName',
            direction: 'asc'
        }
    };

//This factory do the ajax call and get the JSON Data to feed the grid
    itLandingFactory.getIRMSData().then(function (responseData) {
    	$rootScope.gridOptions.data = responseData.data.data;
    });
```

Then I have done a text filtering and then I have CRUD operation and try to reload the grid. So on the success of CRUD operation I have fetched the data again and updated 

> $rootScope.gridOptions.data

using the following code

```
                        itLandingFactory.getIRMSData().then(function (responseData) {
				 $rootScope.gridOptions.data = responseData.data.data;
			 });
```

Then filtered data reloaded. But if I change the filter then the data is only filtering with in the filtered data, not on the whole data. My text filter code as below.

```
<input ng-model="id"
	                               class="md-input"
	                               ng-change="$root.gridActions.filter()"
	                               id="id"
	                               placeholder="Search by Id"
	                               filter-by="id"
	                               filter-type="text"
	                               aria-invalid="false">
```

Any help?

**Additional Comment**

Seems like if you add _predicate_ then only the issue is applicable.

```
sort: {
            predicate: 'empName',
            direction: 'asc'
        }
```

**Comment by tina-tran** [comment]
Hi @suvonkar 

I am having the same issue as yours.
Precisely, I have a initial grid, I filter it with a select (filter-type='text'), then I add new data to the grid, and I make a refresh. The grid does not seem to want to reload and the grid now has only filtered data.

Did you resolve the issue?

Kind regards,
Tina.

**Comment by vikram06** [comment]
Did you resolve the issue?

**Comment by vikram06** [comment]
@suvonkar @tina-tran  I have fixed that issue

**Comment by tina-tran** [comment]
@vikram06 I'm sorry for my late response. I did not fix that issue.
Thank you very much for your help. I will test it out.

**Comment by vikram06** [comment]
Have you checked that one ?

**Comment by tina-tran** [comment]
I've tested this. It does not work for me. I still have the same issue as before:
- Load the grid with initial data.
- Filter the grid with a select.
- Add new data items.
- Refresh the grid programmatically (method refresh())
- The grid still contains only filtered data.

**Comment by vikram06** [comment]
Kindly share your code

**Comment by tina-tran** [comment]
I'm very sorry. I checked again and **removed 1 line** and it works very well now.
Here was my code:
```
for(var i = 0; i < $scope.newMessagesList.length; i++) {
    $scope.globalMessagesGridOptions.data.unshift($scope.newMessagesList[i]);
}
$scope.globalMessagesGridActions.filter(); // <=== This is the line I removed to make it work.
$scope.globalMessagesGridActions.refresh();
```
And even I removed the `filter()`, the grid still filters for me which means that if the new data that I added to the grid doesn't match the filters, it won't appear on the grid. It works exactly as I expected.
Thank you again for your help @vikram06.

**Comment by vikram06** [comment]
Sounds good.... :+1:
